// <auto-generated>
/*
 * Got Issues API
 *
 * A self-hosted, API-first issue and task tracker for internal engineering work.  This document is the product's user-facing documentation as well as its contract: every operation and schema is described for a reader who has never seen the implementation. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using GotIssues.Client.Client;

namespace GotIssues.Client.Model
{
    /// <summary>
    /// The person an issue is assigned to.  Carries the display name as well as the subject so a client can render who holds an issue without a second call — which is what the user projection exists for. 
    /// </summary>
    public partial class Assignee : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Assignee" /> class.
        /// </summary>
        /// <param name="subject">The subject claim identifying the person. This is the identifier: the projection stores no email, and a display name is neither unique nor stable. </param>
        /// <param name="displayName">The person&#39;s display name as their token last carried it, or null if their token carried none. </param>
        [JsonConstructor]
        public Assignee(string subject, Option<string?> displayName = default)
        {
            Subject = subject;
            DisplayNameOption = displayName;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// The subject claim identifying the person. This is the identifier: the projection stores no email, and a display name is neither unique nor stable. 
        /// </summary>
        /// <value>The subject claim identifying the person. This is the identifier: the projection stores no email, and a display name is neither unique nor stable. </value>
        [JsonPropertyName("subject")]
        public string Subject { get; set; }

        /// <summary>
        /// Used to track the state of DisplayName
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> DisplayNameOption { get; private set; }

        /// <summary>
        /// The person&#39;s display name as their token last carried it, or null if their token carried none. 
        /// </summary>
        /// <value>The person&#39;s display name as their token last carried it, or null if their token carried none. </value>
        [JsonPropertyName("displayName")]
        public string? DisplayName { get { return this.DisplayNameOption; } set { this.DisplayNameOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Assignee {\n");
            sb.Append("  Subject: ").Append(Subject).Append("\n");
            sb.Append("  DisplayName: ").Append(DisplayName).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Subject (string) maxLength
            if (this.Subject != null && this.Subject.Length > 255)
            {
                yield return new ValidationResult("Invalid value for Subject, length must be less than 255.", new [] { "Subject" });
            }

            // DisplayName (string) maxLength
            if (this.DisplayName != null && this.DisplayName.Length > 400)
            {
                yield return new ValidationResult("Invalid value for DisplayName, length must be less than 400.", new [] { "DisplayName" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="Assignee" />
    /// </summary>
    public class AssigneeJsonConverter : JsonConverter<Assignee>
    {
        /// <summary>
        /// Deserializes json to <see cref="Assignee" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override Assignee Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> subject = default;
            Option<string?> displayName = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "subject":
                            subject = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "displayName":
                            displayName = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!subject.IsSet)
                throw new ArgumentException("Property is required for class Assignee.", nameof(subject));

            if (subject.IsSet && subject.Value == null)
                throw new ArgumentNullException(nameof(subject), "Property is not nullable for class Assignee.");

            return new Assignee(subject.Value!, displayName);
        }

        /// <summary>
        /// Serializes a <see cref="Assignee" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="assignee"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, Assignee assignee, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, assignee, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="Assignee" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="assignee"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, Assignee assignee, JsonSerializerOptions jsonSerializerOptions)
        {
            if (assignee.Subject == null)
                throw new ArgumentNullException(nameof(assignee.Subject), "Property is required for class Assignee.");

            writer.WriteString("subject", assignee.Subject);

            if (assignee.DisplayNameOption.IsSet)
                if (assignee.DisplayNameOption.Value != null)
                    writer.WriteString("displayName", assignee.DisplayName);
                else
                    writer.WriteNull("displayName");
        }
    }
}
