// <auto-generated>
/*
 * Got Issues API
 *
 * A self-hosted, API-first issue and task tracker for internal engineering work.  This document is the product's user-facing documentation as well as its contract: every operation and schema is described for a reader who has never seen the implementation. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using GotIssues.Client.Client;

namespace GotIssues.Client.Model
{
    /// <summary>
    /// A change of assignment.  There are three ways to send this object and they mean two things:  | Sent | Meaning | | - -- | - -- | | &#x60;{\&quot;subject\&quot;: \&quot;alice\&quot;}&#x60; | assign to &#x60;alice&#x60; | | &#x60;{\&quot;subject\&quot;: null}&#x60; | unassign | | &#x60;{}&#x60; | **unassign** — an absent &#x60;subject&#x60; is read as null |  The third is worth stating plainly rather than leaving to be discovered: a client that forgets to send &#x60;subject&#x60; unassigns the issue and receives 200. The API cannot distinguish an omitted &#x60;subject&#x60; from an explicit null — that is the same limitation this object exists to work around one level up — so it is documented rather than rejected. Omit &#x60;assignment&#x60; entirely to leave the holder alone.  &#x60;subject&#x60; is deliberately **not** listed as required. In JSON Schema &#x60;required&#x60; means \&quot;the property must be present\&quot;, but the C# generator renders it as &#x60;[Required]&#x60;, which means \&quot;must not be null\&quot; — and null is precisely the value that unassigns. Listing it would reject the operation this object exists to express. 
    /// </summary>
    public partial class AssignmentChange : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AssignmentChange" /> class.
        /// </summary>
        /// <param name="subject">The subject of the person to assign, or **null to unassign**.  Control characters are excluded, for the reason every other free-text field in this document excludes them: PostgreSQL cannot store &#x60;U+0000&#x60;, so without this the value reaches the database and fails as an unhandled error rather than as validation. A subject is a token claim and spans one line.  A subject with no user record is rejected with 400: this API assigns to people it has seen, and inventing one silently would produce an assignee no client could render. </param>
        [JsonConstructor]
        public AssignmentChange(Option<string?> subject = default)
        {
            SubjectOption = subject;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Subject
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> SubjectOption { get; private set; }

        /// <summary>
        /// The subject of the person to assign, or **null to unassign**.  Control characters are excluded, for the reason every other free-text field in this document excludes them: PostgreSQL cannot store &#x60;U+0000&#x60;, so without this the value reaches the database and fails as an unhandled error rather than as validation. A subject is a token claim and spans one line.  A subject with no user record is rejected with 400: this API assigns to people it has seen, and inventing one silently would produce an assignee no client could render. 
        /// </summary>
        /// <value>The subject of the person to assign, or **null to unassign**.  Control characters are excluded, for the reason every other free-text field in this document excludes them: PostgreSQL cannot store &#x60;U+0000&#x60;, so without this the value reaches the database and fails as an unhandled error rather than as validation. A subject is a token claim and spans one line.  A subject with no user record is rejected with 400: this API assigns to people it has seen, and inventing one silently would produce an assignee no client could render. </value>
        [JsonPropertyName("subject")]
        public string? Subject { get { return this.SubjectOption; } set { this.SubjectOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AssignmentChange {\n");
            sb.Append("  Subject: ").Append(Subject).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Subject (string) maxLength
            if (this.Subject != null && this.Subject.Length > 255)
            {
                yield return new ValidationResult("Invalid value for Subject, length must be less than 255.", new [] { "Subject" });
            }

            // Subject (string) minLength
            if (this.Subject != null && this.Subject.Length < 1)
            {
                yield return new ValidationResult("Invalid value for Subject, length must be greater than 1.", new [] { "Subject" });
            }

            if (this.SubjectOption.Value != null) {
                // Subject (string) pattern
                Regex regexSubject = new Regex(@"^[^\u0000-\u001F\u007F]+$", RegexOptions.CultureInvariant);

                if (this.SubjectOption.Value != null &&!regexSubject.Match(this.SubjectOption.Value).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Subject, must match a pattern of " + regexSubject, new [] { "Subject" });
                }
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="AssignmentChange" />
    /// </summary>
    public class AssignmentChangeJsonConverter : JsonConverter<AssignmentChange>
    {
        /// <summary>
        /// Deserializes json to <see cref="AssignmentChange" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override AssignmentChange Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> subject = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "subject":
                            subject = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }

            return new AssignmentChange(subject);
        }

        /// <summary>
        /// Serializes a <see cref="AssignmentChange" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="assignmentChange"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, AssignmentChange assignmentChange, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, assignmentChange, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="AssignmentChange" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="assignmentChange"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, AssignmentChange assignmentChange, JsonSerializerOptions jsonSerializerOptions)
        {
            if (assignmentChange.SubjectOption.IsSet)
                if (assignmentChange.SubjectOption.Value != null)
                    writer.WriteString("subject", assignmentChange.Subject);
                else
                    writer.WriteNull("subject");
        }
    }
}
