// <auto-generated>
/*
 * Got Issues API
 *
 * A self-hosted, API-first issue and task tracker for internal engineering work.  This document is the product's user-facing documentation as well as its contract: every operation and schema is described for a reader who has never seen the implementation. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using GotIssues.Client.Client;

namespace GotIssues.Client.Model
{
    /// <summary>
    /// CreatePlaceholderRequest
    /// </summary>
    public partial class CreatePlaceholderRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreatePlaceholderRequest" /> class.
        /// </summary>
        /// <param name="label">An optional human-readable label. Explicitly null is accepted and means the same as omitting it — declared here because the API accepts it, and a contract that forbids what the API allows is as wrong as the reverse. </param>
        [JsonConstructor]
        public CreatePlaceholderRequest(Option<string?> label = default)
        {
            LabelOption = label;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Label
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> LabelOption { get; private set; }

        /// <summary>
        /// An optional human-readable label. Explicitly null is accepted and means the same as omitting it — declared here because the API accepts it, and a contract that forbids what the API allows is as wrong as the reverse. 
        /// </summary>
        /// <value>An optional human-readable label. Explicitly null is accepted and means the same as omitting it — declared here because the API accepts it, and a contract that forbids what the API allows is as wrong as the reverse. </value>
        [JsonPropertyName("label")]
        public string? Label { get { return this.LabelOption; } set { this.LabelOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreatePlaceholderRequest {\n");
            sb.Append("  Label: ").Append(Label).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Label (string) maxLength
            if (this.Label != null && this.Label.Length > 200)
            {
                yield return new ValidationResult("Invalid value for Label, length must be less than 200.", new [] { "Label" });
            }

            // Label (string) minLength
            if (this.Label != null && this.Label.Length < 1)
            {
                yield return new ValidationResult("Invalid value for Label, length must be greater than 1.", new [] { "Label" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="CreatePlaceholderRequest" />
    /// </summary>
    public class CreatePlaceholderRequestJsonConverter : JsonConverter<CreatePlaceholderRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="CreatePlaceholderRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override CreatePlaceholderRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> label = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "label":
                            label = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }

            return new CreatePlaceholderRequest(label);
        }

        /// <summary>
        /// Serializes a <see cref="CreatePlaceholderRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="createPlaceholderRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, CreatePlaceholderRequest createPlaceholderRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, createPlaceholderRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="CreatePlaceholderRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="createPlaceholderRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, CreatePlaceholderRequest createPlaceholderRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (createPlaceholderRequest.LabelOption.IsSet)
                if (createPlaceholderRequest.LabelOption.Value != null)
                    writer.WriteString("label", createPlaceholderRequest.Label);
                else
                    writer.WriteNull("label");
        }
    }
}
