// <auto-generated>
/*
 * Got Issues API
 *
 * A self-hosted, API-first issue and task tracker for internal engineering work.  This document is the product's user-facing documentation as well as its contract: every operation and schema is described for a reader who has never seen the implementation. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using GotIssues.Client.Client;

namespace GotIssues.Client.Model
{
    /// <summary>
    /// CreateProjectRequest
    /// </summary>
    public partial class CreateProjectRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateProjectRequest" /> class.
        /// </summary>
        /// <param name="key">The key this project&#39;s issues are numbered under, for example &#x60;GOTI&#x60;. Cannot be changed afterwards, so it is worth choosing deliberately. </param>
        /// <param name="name">The project&#39;s display name. C0 control characters and DEL are excluded: &#x60;U+0000&#x60; cannot be stored by PostgreSQL at all, and the rest of the range carries tabs and line breaks a display name has no use for. </param>
        [JsonConstructor]
        public CreateProjectRequest(string key, string name)
        {
            Key = key;
            Name = name;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// The key this project&#39;s issues are numbered under, for example &#x60;GOTI&#x60;. Cannot be changed afterwards, so it is worth choosing deliberately. 
        /// </summary>
        /// <value>The key this project&#39;s issues are numbered under, for example &#x60;GOTI&#x60;. Cannot be changed afterwards, so it is worth choosing deliberately. </value>
        [JsonPropertyName("key")]
        public string Key { get; set; }

        /// <summary>
        /// The project&#39;s display name. C0 control characters and DEL are excluded: &#x60;U+0000&#x60; cannot be stored by PostgreSQL at all, and the rest of the range carries tabs and line breaks a display name has no use for. 
        /// </summary>
        /// <value>The project&#39;s display name. C0 control characters and DEL are excluded: &#x60;U+0000&#x60; cannot be stored by PostgreSQL at all, and the rest of the range carries tabs and line breaks a display name has no use for. </value>
        [JsonPropertyName("name")]
        public string Name { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateProjectRequest {\n");
            sb.Append("  Key: ").Append(Key).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Key (string) maxLength
            if (this.Key != null && this.Key.Length > 10)
            {
                yield return new ValidationResult("Invalid value for Key, length must be less than 10.", new [] { "Key" });
            }

            // Key (string) minLength
            if (this.Key != null && this.Key.Length < 2)
            {
                yield return new ValidationResult("Invalid value for Key, length must be greater than 2.", new [] { "Key" });
            }

            if (this.Key != null) {
                // Key (string) pattern
                Regex regexKey = new Regex(@"^[A-Z][A-Z0-9]{1,9}$", RegexOptions.CultureInvariant);

                if (!regexKey.Match(this.Key).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Key, must match a pattern of " + regexKey, new [] { "Key" });
                }
            }

            // Name (string) maxLength
            if (this.Name != null && this.Name.Length > 200)
            {
                yield return new ValidationResult("Invalid value for Name, length must be less than 200.", new [] { "Name" });
            }

            // Name (string) minLength
            if (this.Name != null && this.Name.Length < 1)
            {
                yield return new ValidationResult("Invalid value for Name, length must be greater than 1.", new [] { "Name" });
            }

            if (this.Name != null) {
                // Name (string) pattern
                Regex regexName = new Regex(@"^[^\u0000-\u001F\u007F]+$", RegexOptions.CultureInvariant);

                if (!regexName.Match(this.Name).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Name, must match a pattern of " + regexName, new [] { "Name" });
                }
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="CreateProjectRequest" />
    /// </summary>
    public class CreateProjectRequestJsonConverter : JsonConverter<CreateProjectRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="CreateProjectRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override CreateProjectRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> key = default;
            Option<string?> name = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "key":
                            key = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!key.IsSet)
                throw new ArgumentException("Property is required for class CreateProjectRequest.", nameof(key));

            if (!name.IsSet)
                throw new ArgumentException("Property is required for class CreateProjectRequest.", nameof(name));

            if (key.IsSet && key.Value == null)
                throw new ArgumentNullException(nameof(key), "Property is not nullable for class CreateProjectRequest.");

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class CreateProjectRequest.");

            return new CreateProjectRequest(key.Value!, name.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="CreateProjectRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="createProjectRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, CreateProjectRequest createProjectRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, createProjectRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="CreateProjectRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="createProjectRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, CreateProjectRequest createProjectRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (createProjectRequest.Key == null)
                throw new ArgumentNullException(nameof(createProjectRequest.Key), "Property is required for class CreateProjectRequest.");

            if (createProjectRequest.Name == null)
                throw new ArgumentNullException(nameof(createProjectRequest.Name), "Property is required for class CreateProjectRequest.");

            writer.WriteString("key", createProjectRequest.Key);

            writer.WriteString("name", createProjectRequest.Name);
        }
    }
}
