// <auto-generated>
/*
 * Got Issues API
 *
 * A self-hosted, API-first issue and task tracker for internal engineering work.  This document is the product's user-facing documentation as well as its contract: every operation and schema is described for a reader who has never seen the implementation. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using GotIssues.Client.Client;

namespace GotIssues.Client.Model
{
    /// <summary>
    /// CreateIssueRequest
    /// </summary>
    public partial class CreateIssueRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateIssueRequest" /> class.
        /// </summary>
        /// <param name="title">A one-line summary. C0 control characters and DEL are excluded — see &#x60;Issue.title&#x60; for both reasons and for the limit this constraint deliberately stops at.  &#x60;U+0085&#x60; and &#x60;U+2028&#x60; are accepted: the constraint is the narrow, checkable one. </param>
        /// <param name="description">Optional free text; multi-line is expected. Explicitly null means the same as omitting it. </param>
        [JsonConstructor]
        public CreateIssueRequest(string title, Option<string?> description = default)
        {
            Title = title;
            DescriptionOption = description;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// A one-line summary. C0 control characters and DEL are excluded — see &#x60;Issue.title&#x60; for both reasons and for the limit this constraint deliberately stops at.  &#x60;U+0085&#x60; and &#x60;U+2028&#x60; are accepted: the constraint is the narrow, checkable one. 
        /// </summary>
        /// <value>A one-line summary. C0 control characters and DEL are excluded — see &#x60;Issue.title&#x60; for both reasons and for the limit this constraint deliberately stops at.  &#x60;U+0085&#x60; and &#x60;U+2028&#x60; are accepted: the constraint is the narrow, checkable one. </value>
        [JsonPropertyName("title")]
        public string Title { get; set; }

        /// <summary>
        /// Used to track the state of Description
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> DescriptionOption { get; private set; }

        /// <summary>
        /// Optional free text; multi-line is expected. Explicitly null means the same as omitting it. 
        /// </summary>
        /// <value>Optional free text; multi-line is expected. Explicitly null means the same as omitting it. </value>
        [JsonPropertyName("description")]
        public string? Description { get { return this.DescriptionOption; } set { this.DescriptionOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateIssueRequest {\n");
            sb.Append("  Title: ").Append(Title).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Title (string) maxLength
            if (this.Title != null && this.Title.Length > 200)
            {
                yield return new ValidationResult("Invalid value for Title, length must be less than 200.", new [] { "Title" });
            }

            // Title (string) minLength
            if (this.Title != null && this.Title.Length < 1)
            {
                yield return new ValidationResult("Invalid value for Title, length must be greater than 1.", new [] { "Title" });
            }

            if (this.Title != null) {
                // Title (string) pattern
                Regex regexTitle = new Regex(@"^[^\u0000-\u001F\u007F]+$", RegexOptions.CultureInvariant);

                if (!regexTitle.Match(this.Title).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Title, must match a pattern of " + regexTitle, new [] { "Title" });
                }
            }

            // Description (string) maxLength
            if (this.Description != null && this.Description.Length > 10000)
            {
                yield return new ValidationResult("Invalid value for Description, length must be less than 10000.", new [] { "Description" });
            }

            if (this.DescriptionOption.Value != null) {
                // Description (string) pattern
                Regex regexDescription = new Regex(@"^[^\u0000]*$", RegexOptions.CultureInvariant);

                if (this.DescriptionOption.Value != null &&!regexDescription.Match(this.DescriptionOption.Value).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Description, must match a pattern of " + regexDescription, new [] { "Description" });
                }
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="CreateIssueRequest" />
    /// </summary>
    public class CreateIssueRequestJsonConverter : JsonConverter<CreateIssueRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="CreateIssueRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override CreateIssueRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> title = default;
            Option<string?> description = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "title":
                            title = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "description":
                            description = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!title.IsSet)
                throw new ArgumentException("Property is required for class CreateIssueRequest.", nameof(title));

            if (title.IsSet && title.Value == null)
                throw new ArgumentNullException(nameof(title), "Property is not nullable for class CreateIssueRequest.");

            return new CreateIssueRequest(title.Value!, description);
        }

        /// <summary>
        /// Serializes a <see cref="CreateIssueRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="createIssueRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, CreateIssueRequest createIssueRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, createIssueRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="CreateIssueRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="createIssueRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, CreateIssueRequest createIssueRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (createIssueRequest.Title == null)
                throw new ArgumentNullException(nameof(createIssueRequest.Title), "Property is required for class CreateIssueRequest.");

            writer.WriteString("title", createIssueRequest.Title);

            if (createIssueRequest.DescriptionOption.IsSet)
                if (createIssueRequest.DescriptionOption.Value != null)
                    writer.WriteString("description", createIssueRequest.Description);
                else
                    writer.WriteNull("description");
        }
    }
}
