// <auto-generated>
/*
 * Got Issues API
 *
 * A self-hosted, API-first issue and task tracker for internal engineering work.  This document is the product's user-facing documentation as well as its contract: every operation and schema is described for a reader who has never seen the implementation. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using GotIssues.Client.Client;

namespace GotIssues.Client.Model
{
    /// <summary>
    /// A unit of work inside a project.
    /// </summary>
    public partial class Issue : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Issue" /> class.
        /// </summary>
        /// <param name="id">The issue&#39;s identifier.</param>
        /// <param name="key">The issue&#39;s key: the project&#39;s key, a hyphen, and the number allocated within that project. This is the identifier people quote. </param>
        /// <param name="projectKey">The key of the project this issue belongs to.</param>
        /// <param name="number">The issue&#39;s number within its project. Allocated by the server, starting at 1 in each project, and never reused.  The maximum is not arbitrary: it is the largest number &#x60;key&#x60; can express, since that pattern allows nine digits. Without it the two fields could disagree — a number of ten digits would produce a key violating the very pattern this document declares, and the issue would be unreadable through the only operation that fetches one. A project reaching this limit is refused with 409 rather than issued a key it cannot use. </param>
        /// <param name="title">A one-line summary. C0 control characters and DEL are excluded, for the same two reasons a project name excludes them: PostgreSQL cannot store &#x60;U+0000&#x60; at all, and the ASCII line breaks and tabs in that range have no place in a title.  Deliberately **not** full Unicode line-break handling: &#x60;U+0085&#x60; and &#x60;U+2028&#x60; are accepted. Refinement asked this ticket to decide rather than inherit the limit, and the decision is to keep the constraint the narrow, checkable one — a title carrying an exotic separator is a cosmetic problem, while a title carrying &#x60;U+0000&#x60; cannot be stored at all. </param>
        /// <param name="type">type</param>
        /// <param name="status">status</param>
        /// <param name="priority">priority</param>
        /// <param name="createdAt">When the issue was created, in UTC.</param>
        /// <param name="description">Optional free text. Multi-line **by design** — unlike a title, this is where the reasoning goes, so line breaks are permitted and only &#x60;U+0000&#x60; is excluded, because PostgreSQL cannot store it in any text column.  That difference is deliberate: the constraint on a title is about being one line, the constraint here is about being storable, and they are not the same rule (recorded on T-0005 from T-0004&#39;s review). </param>
        /// <param name="assignee">assignee</param>
        [JsonConstructor]
        public Issue(Guid id, string key, string projectKey, int number, string title, IssueType type, IssueStatus status, IssuePriority priority, DateTime createdAt, Option<string?> description = default, Option<Assignee?> assignee = default)
        {
            Id = id;
            Key = key;
            ProjectKey = projectKey;
            Number = number;
            Title = title;
            Type = type;
            Status = status;
            Priority = priority;
            CreatedAt = createdAt;
            DescriptionOption = description;
            AssigneeOption = assignee;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [JsonPropertyName("type")]
        public IssueType Type { get; set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [JsonPropertyName("status")]
        public IssueStatus Status { get; set; }

        /// <summary>
        /// Gets or Sets Priority
        /// </summary>
        [JsonPropertyName("priority")]
        public IssuePriority Priority { get; set; }

        /// <summary>
        /// The issue&#39;s identifier.
        /// </summary>
        /// <value>The issue&#39;s identifier.</value>
        [JsonPropertyName("id")]
        public Guid Id { get; set; }

        /// <summary>
        /// The issue&#39;s key: the project&#39;s key, a hyphen, and the number allocated within that project. This is the identifier people quote. 
        /// </summary>
        /// <value>The issue&#39;s key: the project&#39;s key, a hyphen, and the number allocated within that project. This is the identifier people quote. </value>
        [JsonPropertyName("key")]
        public string Key { get; set; }

        /// <summary>
        /// The key of the project this issue belongs to.
        /// </summary>
        /// <value>The key of the project this issue belongs to.</value>
        [JsonPropertyName("projectKey")]
        public string ProjectKey { get; set; }

        /// <summary>
        /// The issue&#39;s number within its project. Allocated by the server, starting at 1 in each project, and never reused.  The maximum is not arbitrary: it is the largest number &#x60;key&#x60; can express, since that pattern allows nine digits. Without it the two fields could disagree — a number of ten digits would produce a key violating the very pattern this document declares, and the issue would be unreadable through the only operation that fetches one. A project reaching this limit is refused with 409 rather than issued a key it cannot use. 
        /// </summary>
        /// <value>The issue&#39;s number within its project. Allocated by the server, starting at 1 in each project, and never reused.  The maximum is not arbitrary: it is the largest number &#x60;key&#x60; can express, since that pattern allows nine digits. Without it the two fields could disagree — a number of ten digits would produce a key violating the very pattern this document declares, and the issue would be unreadable through the only operation that fetches one. A project reaching this limit is refused with 409 rather than issued a key it cannot use. </value>
        [JsonPropertyName("number")]
        public int Number { get; set; }

        /// <summary>
        /// A one-line summary. C0 control characters and DEL are excluded, for the same two reasons a project name excludes them: PostgreSQL cannot store &#x60;U+0000&#x60; at all, and the ASCII line breaks and tabs in that range have no place in a title.  Deliberately **not** full Unicode line-break handling: &#x60;U+0085&#x60; and &#x60;U+2028&#x60; are accepted. Refinement asked this ticket to decide rather than inherit the limit, and the decision is to keep the constraint the narrow, checkable one — a title carrying an exotic separator is a cosmetic problem, while a title carrying &#x60;U+0000&#x60; cannot be stored at all. 
        /// </summary>
        /// <value>A one-line summary. C0 control characters and DEL are excluded, for the same two reasons a project name excludes them: PostgreSQL cannot store &#x60;U+0000&#x60; at all, and the ASCII line breaks and tabs in that range have no place in a title.  Deliberately **not** full Unicode line-break handling: &#x60;U+0085&#x60; and &#x60;U+2028&#x60; are accepted. Refinement asked this ticket to decide rather than inherit the limit, and the decision is to keep the constraint the narrow, checkable one — a title carrying an exotic separator is a cosmetic problem, while a title carrying &#x60;U+0000&#x60; cannot be stored at all. </value>
        [JsonPropertyName("title")]
        public string Title { get; set; }

        /// <summary>
        /// When the issue was created, in UTC.
        /// </summary>
        /// <value>When the issue was created, in UTC.</value>
        [JsonPropertyName("createdAt")]
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// Used to track the state of Description
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> DescriptionOption { get; private set; }

        /// <summary>
        /// Optional free text. Multi-line **by design** — unlike a title, this is where the reasoning goes, so line breaks are permitted and only &#x60;U+0000&#x60; is excluded, because PostgreSQL cannot store it in any text column.  That difference is deliberate: the constraint on a title is about being one line, the constraint here is about being storable, and they are not the same rule (recorded on T-0005 from T-0004&#39;s review). 
        /// </summary>
        /// <value>Optional free text. Multi-line **by design** — unlike a title, this is where the reasoning goes, so line breaks are permitted and only &#x60;U+0000&#x60; is excluded, because PostgreSQL cannot store it in any text column.  That difference is deliberate: the constraint on a title is about being one line, the constraint here is about being storable, and they are not the same rule (recorded on T-0005 from T-0004&#39;s review). </value>
        [JsonPropertyName("description")]
        public string? Description { get { return this.DescriptionOption; } set { this.DescriptionOption = new(value); } }

        /// <summary>
        /// Used to track the state of Assignee
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Assignee?> AssigneeOption { get; private set; }

        /// <summary>
        /// Gets or Sets Assignee
        /// </summary>
        [JsonPropertyName("assignee")]
        public Assignee? Assignee { get { return this.AssigneeOption; } set { this.AssigneeOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Issue {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Key: ").Append(Key).Append("\n");
            sb.Append("  ProjectKey: ").Append(ProjectKey).Append("\n");
            sb.Append("  Number: ").Append(Number).Append("\n");
            sb.Append("  Title: ").Append(Title).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  Priority: ").Append(Priority).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  Assignee: ").Append(Assignee).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            if (this.Key != null) {
                // Key (string) pattern
                Regex regexKey = new Regex(@"^[A-Z][A-Z0-9]{1,9}-[1-9][0-9]{0,8}$", RegexOptions.CultureInvariant);

                if (!regexKey.Match(this.Key).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Key, must match a pattern of " + regexKey, new [] { "Key" });
                }
            }

            if (this.ProjectKey != null) {
                // ProjectKey (string) pattern
                Regex regexProjectKey = new Regex(@"^[A-Z][A-Z0-9]{1,9}$", RegexOptions.CultureInvariant);

                if (!regexProjectKey.Match(this.ProjectKey).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for ProjectKey, must match a pattern of " + regexProjectKey, new [] { "ProjectKey" });
                }
            }

            // Number (int) maximum
            if (this.Number > (int)999999999)
            {
                yield return new ValidationResult("Invalid value for Number, must be a value less than or equal to 999999999.", new [] { "Number" });
            }

            // Number (int) minimum
            if (this.Number < (int)1)
            {
                yield return new ValidationResult("Invalid value for Number, must be a value greater than or equal to 1.", new [] { "Number" });
            }

            // Title (string) maxLength
            if (this.Title != null && this.Title.Length > 200)
            {
                yield return new ValidationResult("Invalid value for Title, length must be less than 200.", new [] { "Title" });
            }

            // Title (string) minLength
            if (this.Title != null && this.Title.Length < 1)
            {
                yield return new ValidationResult("Invalid value for Title, length must be greater than 1.", new [] { "Title" });
            }

            if (this.Title != null) {
                // Title (string) pattern
                Regex regexTitle = new Regex(@"^[^\u0000-\u001F\u007F]+$", RegexOptions.CultureInvariant);

                if (!regexTitle.Match(this.Title).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Title, must match a pattern of " + regexTitle, new [] { "Title" });
                }
            }

            // Description (string) maxLength
            if (this.Description != null && this.Description.Length > 10000)
            {
                yield return new ValidationResult("Invalid value for Description, length must be less than 10000.", new [] { "Description" });
            }

            if (this.DescriptionOption.Value != null) {
                // Description (string) pattern
                Regex regexDescription = new Regex(@"^[^\u0000]*$", RegexOptions.CultureInvariant);

                if (this.DescriptionOption.Value != null &&!regexDescription.Match(this.DescriptionOption.Value).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Description, must match a pattern of " + regexDescription, new [] { "Description" });
                }
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="Issue" />
    /// </summary>
    public class IssueJsonConverter : JsonConverter<Issue>
    {
        /// <summary>
        /// The format to use to serialize CreatedAt
        /// </summary>
        public static string CreatedAtFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="Issue" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override Issue Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<Guid?> id = default;
            Option<string?> key = default;
            Option<string?> projectKey = default;
            Option<int?> number = default;
            Option<string?> title = default;
            Option<IssueType?> type = default;
            Option<IssueStatus?> status = default;
            Option<IssuePriority?> priority = default;
            Option<DateTime?> createdAt = default;
            Option<string?> description = default;
            Option<Assignee?> assignee = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            id = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "key":
                            key = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "projectKey":
                            projectKey = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "number":
                            number = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "title":
                            title = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "type":
                            string? typeRawValue = utf8JsonReader.GetString();
                            if (typeRawValue != null)
                                type = new Option<IssueType?>(IssueTypeValueConverter.FromStringOrDefault(typeRawValue));
                            break;
                        case "status":
                            string? statusRawValue = utf8JsonReader.GetString();
                            if (statusRawValue != null)
                                status = new Option<IssueStatus?>(IssueStatusValueConverter.FromStringOrDefault(statusRawValue));
                            break;
                        case "priority":
                            string? priorityRawValue = utf8JsonReader.GetString();
                            if (priorityRawValue != null)
                                priority = new Option<IssuePriority?>(IssuePriorityValueConverter.FromStringOrDefault(priorityRawValue));
                            break;
                        case "createdAt":
                            createdAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "description":
                            description = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "assignee":
                            assignee = new Option<Assignee?>(JsonSerializer.Deserialize<Assignee>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!id.IsSet)
                throw new ArgumentException("Property is required for class Issue.", nameof(id));

            if (!key.IsSet)
                throw new ArgumentException("Property is required for class Issue.", nameof(key));

            if (!projectKey.IsSet)
                throw new ArgumentException("Property is required for class Issue.", nameof(projectKey));

            if (!number.IsSet)
                throw new ArgumentException("Property is required for class Issue.", nameof(number));

            if (!title.IsSet)
                throw new ArgumentException("Property is required for class Issue.", nameof(title));

            if (!type.IsSet)
                throw new ArgumentException("Property is required for class Issue.", nameof(type));

            if (!status.IsSet)
                throw new ArgumentException("Property is required for class Issue.", nameof(status));

            if (!priority.IsSet)
                throw new ArgumentException("Property is required for class Issue.", nameof(priority));

            if (!createdAt.IsSet)
                throw new ArgumentException("Property is required for class Issue.", nameof(createdAt));

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class Issue.");

            if (key.IsSet && key.Value == null)
                throw new ArgumentNullException(nameof(key), "Property is not nullable for class Issue.");

            if (projectKey.IsSet && projectKey.Value == null)
                throw new ArgumentNullException(nameof(projectKey), "Property is not nullable for class Issue.");

            if (number.IsSet && number.Value == null)
                throw new ArgumentNullException(nameof(number), "Property is not nullable for class Issue.");

            if (title.IsSet && title.Value == null)
                throw new ArgumentNullException(nameof(title), "Property is not nullable for class Issue.");

            if (type.IsSet && type.Value == null)
                throw new ArgumentNullException(nameof(type), "Property is not nullable for class Issue.");

            if (status.IsSet && status.Value == null)
                throw new ArgumentNullException(nameof(status), "Property is not nullable for class Issue.");

            if (priority.IsSet && priority.Value == null)
                throw new ArgumentNullException(nameof(priority), "Property is not nullable for class Issue.");

            if (createdAt.IsSet && createdAt.Value == null)
                throw new ArgumentNullException(nameof(createdAt), "Property is not nullable for class Issue.");

            return new Issue(id.Value!.Value!, key.Value!, projectKey.Value!, number.Value!.Value!, title.Value!, type.Value!.Value!, status.Value!.Value!, priority.Value!.Value!, createdAt.Value!.Value!, description, assignee);
        }

        /// <summary>
        /// Serializes a <see cref="Issue" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="issue"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, Issue issue, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, issue, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="Issue" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="issue"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, Issue issue, JsonSerializerOptions jsonSerializerOptions)
        {
            if (issue.Key == null)
                throw new ArgumentNullException(nameof(issue.Key), "Property is required for class Issue.");

            if (issue.ProjectKey == null)
                throw new ArgumentNullException(nameof(issue.ProjectKey), "Property is required for class Issue.");

            if (issue.Title == null)
                throw new ArgumentNullException(nameof(issue.Title), "Property is required for class Issue.");

            writer.WriteString("id", issue.Id);

            writer.WriteString("key", issue.Key);

            writer.WriteString("projectKey", issue.ProjectKey);

            writer.WriteNumber("number", issue.Number);

            writer.WriteString("title", issue.Title);

            var typeRawValue = IssueTypeValueConverter.ToJsonValue(issue.Type);
            writer.WriteString("type", typeRawValue);

            var statusRawValue = IssueStatusValueConverter.ToJsonValue(issue.Status);
            writer.WriteString("status", statusRawValue);

            var priorityRawValue = IssuePriorityValueConverter.ToJsonValue(issue.Priority);
            writer.WriteString("priority", priorityRawValue);

            writer.WriteString("createdAt", issue.CreatedAt.ToString(CreatedAtFormat));

            if (issue.DescriptionOption.IsSet)
                if (issue.DescriptionOption.Value != null)
                    writer.WriteString("description", issue.Description);
                else
                    writer.WriteNull("description");

            if (issue.AssigneeOption.IsSet)
                if (issue.AssigneeOption.Value != null)
                {
                    writer.WritePropertyName("assignee");
                    JsonSerializer.Serialize(writer, issue.Assignee, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("assignee");
        }
    }
}
