// <auto-generated>
/*
 * Got Issues API
 *
 * A self-hosted, API-first issue and task tracker for internal engineering work.  This document is the product's user-facing documentation as well as its contract: every operation and schema is described for a reader who has never seen the implementation. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using GotIssues.Client.Client;

namespace GotIssues.Client.Model
{
    /// <summary>
    /// How urgent the work is. Three levels, because &#x60;critical&#x60; reliably becomes a second &#x60;high&#x60;. 
    /// </summary>
    /// <value>How urgent the work is. Three levels, because &#x60;critical&#x60; reliably becomes a second &#x60;high&#x60;. </value>
    public enum IssuePriority
    {
        /// <summary>
        /// Enum Low for value: low
        /// </summary>
        Low = 1,

        /// <summary>
        /// Enum Normal for value: normal
        /// </summary>
        Normal = 2,

        /// <summary>
        /// Enum High for value: high
        /// </summary>
        High = 3
    }

    /// <summary>
    /// Converts <see cref="IssuePriority"/> to and from the JSON value
    /// </summary>
    public static class IssuePriorityValueConverter
    {
        /// <summary>
        /// Parses a given value to <see cref="IssuePriority"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static IssuePriority FromString(string value)
        {
            if (value.Equals("low"))
                return IssuePriority.Low;

            if (value.Equals("normal"))
                return IssuePriority.Normal;

            if (value.Equals("high"))
                return IssuePriority.High;

            throw new NotImplementedException($"Could not convert value to type IssuePriority: '{value}'");
        }

        /// <summary>
        /// Parses a given value to <see cref="IssuePriority"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static IssuePriority? FromStringOrDefault(string value)
        {
            if (value.Equals("low"))
                return IssuePriority.Low;

            if (value.Equals("normal"))
                return IssuePriority.Normal;

            if (value.Equals("high"))
                return IssuePriority.High;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="IssuePriority"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ToJsonValue(IssuePriority value)
        {
            if (value == IssuePriority.Low)
                return "low";

            if (value == IssuePriority.Normal)
                return "normal";

            if (value == IssuePriority.High)
                return "high";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="IssuePriority"/>
    /// </summary>
    /// <exception cref="NotImplementedException"></exception>
    public class IssuePriorityJsonConverter : JsonConverter<IssuePriority>
    {
        /// <summary>
        /// Returns a  from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override IssuePriority Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            IssuePriority? result = rawValue == null
                ? null
                : IssuePriorityValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the IssuePriority to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="issuePriority"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, IssuePriority issuePriority, JsonSerializerOptions options)
        {
            writer.WriteStringValue(IssuePriorityValueConverter.ToJsonValue(issuePriority).ToString());
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="IssuePriority"/>
    /// </summary>
    public class IssuePriorityNullableJsonConverter : JsonConverter<IssuePriority?>
    {
        /// <summary>
        /// Returns a IssuePriority from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override IssuePriority? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            IssuePriority? result = rawValue == null
                ? null
                : IssuePriorityValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the IssuePriority to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="issuePriority"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, IssuePriority? issuePriority, JsonSerializerOptions options)
        {
            writer.WriteStringValue(issuePriority.HasValue ? IssuePriorityValueConverter.ToJsonValue(issuePriority.Value).ToString() : "null");
        }
    }
}
