// <auto-generated>
/*
 * Got Issues API
 *
 * A self-hosted, API-first issue and task tracker for internal engineering work.  This document is the product's user-facing documentation as well as its contract: every operation and schema is described for a reader who has never seen the implementation. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using GotIssues.Client.Client;

namespace GotIssues.Client.Model
{
    /// <summary>
    /// What kind of work this is. Two values, deliberately: &#x60;story&#x60; and &#x60;epic&#x60; imply a planning model this product does not have, and adding a value later is additive while renaming one is a breaking change for every generated client. 
    /// </summary>
    /// <value>What kind of work this is. Two values, deliberately: &#x60;story&#x60; and &#x60;epic&#x60; imply a planning model this product does not have, and adding a value later is additive while renaming one is a breaking change for every generated client. </value>
    public enum IssueType
    {
        /// <summary>
        /// Enum Bug for value: bug
        /// </summary>
        Bug = 1,

        /// <summary>
        /// Enum Task for value: task
        /// </summary>
        Task = 2
    }

    /// <summary>
    /// Converts <see cref="IssueType"/> to and from the JSON value
    /// </summary>
    public static class IssueTypeValueConverter
    {
        /// <summary>
        /// Parses a given value to <see cref="IssueType"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static IssueType FromString(string value)
        {
            if (value.Equals("bug"))
                return IssueType.Bug;

            if (value.Equals("task"))
                return IssueType.Task;

            throw new NotImplementedException($"Could not convert value to type IssueType: '{value}'");
        }

        /// <summary>
        /// Parses a given value to <see cref="IssueType"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static IssueType? FromStringOrDefault(string value)
        {
            if (value.Equals("bug"))
                return IssueType.Bug;

            if (value.Equals("task"))
                return IssueType.Task;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="IssueType"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ToJsonValue(IssueType value)
        {
            if (value == IssueType.Bug)
                return "bug";

            if (value == IssueType.Task)
                return "task";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="IssueType"/>
    /// </summary>
    /// <exception cref="NotImplementedException"></exception>
    public class IssueTypeJsonConverter : JsonConverter<IssueType>
    {
        /// <summary>
        /// Returns a  from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override IssueType Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            IssueType? result = rawValue == null
                ? null
                : IssueTypeValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the IssueType to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="issueType"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, IssueType issueType, JsonSerializerOptions options)
        {
            writer.WriteStringValue(IssueTypeValueConverter.ToJsonValue(issueType).ToString());
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="IssueType"/>
    /// </summary>
    public class IssueTypeNullableJsonConverter : JsonConverter<IssueType?>
    {
        /// <summary>
        /// Returns a IssueType from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override IssueType? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            IssueType? result = rawValue == null
                ? null
                : IssueTypeValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the IssueType to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="issueType"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, IssueType? issueType, JsonSerializerOptions options)
        {
            writer.WriteStringValue(issueType.HasValue ? IssueTypeValueConverter.ToJsonValue(issueType.Value).ToString() : "null");
        }
    }
}
