// <auto-generated>
/*
 * Got Issues API
 *
 * A self-hosted, API-first issue and task tracker for internal engineering work.  This document is the product's user-facing documentation as well as its contract: every operation and schema is described for a reader who has never seen the implementation. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using GotIssues.Client.Client;

namespace GotIssues.Client.Model
{
    /// <summary>
    /// Where the work stands. Any value may follow any other — there are no transition rules, by design.  &#x60;in_review&#x60; was considered and deliberately left out: it is the first status that invites the transition rules this API does not have. Adding it later is the additive direction. 
    /// </summary>
    /// <value>Where the work stands. Any value may follow any other — there are no transition rules, by design.  &#x60;in_review&#x60; was considered and deliberately left out: it is the first status that invites the transition rules this API does not have. Adding it later is the additive direction. </value>
    public enum IssueStatus
    {
        /// <summary>
        /// Enum Open for value: open
        /// </summary>
        Open = 1,

        /// <summary>
        /// Enum InProgress for value: in_progress
        /// </summary>
        InProgress = 2,

        /// <summary>
        /// Enum Done for value: done
        /// </summary>
        Done = 3
    }

    /// <summary>
    /// Converts <see cref="IssueStatus"/> to and from the JSON value
    /// </summary>
    public static class IssueStatusValueConverter
    {
        /// <summary>
        /// Parses a given value to <see cref="IssueStatus"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static IssueStatus FromString(string value)
        {
            if (value.Equals("open"))
                return IssueStatus.Open;

            if (value.Equals("in_progress"))
                return IssueStatus.InProgress;

            if (value.Equals("done"))
                return IssueStatus.Done;

            throw new NotImplementedException($"Could not convert value to type IssueStatus: '{value}'");
        }

        /// <summary>
        /// Parses a given value to <see cref="IssueStatus"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static IssueStatus? FromStringOrDefault(string value)
        {
            if (value.Equals("open"))
                return IssueStatus.Open;

            if (value.Equals("in_progress"))
                return IssueStatus.InProgress;

            if (value.Equals("done"))
                return IssueStatus.Done;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="IssueStatus"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ToJsonValue(IssueStatus value)
        {
            if (value == IssueStatus.Open)
                return "open";

            if (value == IssueStatus.InProgress)
                return "in_progress";

            if (value == IssueStatus.Done)
                return "done";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="IssueStatus"/>
    /// </summary>
    /// <exception cref="NotImplementedException"></exception>
    public class IssueStatusJsonConverter : JsonConverter<IssueStatus>
    {
        /// <summary>
        /// Returns a  from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override IssueStatus Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            IssueStatus? result = rawValue == null
                ? null
                : IssueStatusValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the IssueStatus to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="issueStatus"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, IssueStatus issueStatus, JsonSerializerOptions options)
        {
            writer.WriteStringValue(IssueStatusValueConverter.ToJsonValue(issueStatus).ToString());
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="IssueStatus"/>
    /// </summary>
    public class IssueStatusNullableJsonConverter : JsonConverter<IssueStatus?>
    {
        /// <summary>
        /// Returns a IssueStatus from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override IssueStatus? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            IssueStatus? result = rawValue == null
                ? null
                : IssueStatusValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the IssueStatus to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="issueStatus"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, IssueStatus? issueStatus, JsonSerializerOptions options)
        {
            writer.WriteStringValue(issueStatus.HasValue ? IssueStatusValueConverter.ToJsonValue(issueStatus.Value).ToString() : "null");
        }
    }
}
