// <auto-generated>
/*
 * Got Issues API
 *
 * A self-hosted, API-first issue and task tracker for internal engineering work.  This document is the product's user-facing documentation as well as its contract: every operation and schema is described for a reader who has never seen the implementation. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using GotIssues.Client.Client;

namespace GotIssues.Client.Model
{
    /// <summary>
    /// Every field is optional. An omitted field is left unchanged; this is a partial update, not a replacement. 
    /// </summary>
    public partial class UpdateIssueRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateIssueRequest" /> class.
        /// </summary>
        /// <param name="type">type</param>
        /// <param name="status">status</param>
        /// <param name="priority">priority</param>
        /// <param name="assignment">assignment</param>
        [JsonConstructor]
        public UpdateIssueRequest(Option<IssueType?> type = default, Option<IssueStatus?> status = default, Option<IssuePriority?> priority = default, Option<AssignmentChange?> assignment = default)
        {
            TypeOption = type;
            StatusOption = status;
            PriorityOption = priority;
            AssignmentOption = assignment;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Type
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<IssueType?> TypeOption { get; private set; }

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [JsonPropertyName("type")]
        public IssueType? Type { get { return this.TypeOption; } set { this.TypeOption = new(value); } }

        /// <summary>
        /// Used to track the state of Status
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<IssueStatus?> StatusOption { get; private set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [JsonPropertyName("status")]
        public IssueStatus? Status { get { return this.StatusOption; } set { this.StatusOption = new(value); } }

        /// <summary>
        /// Used to track the state of Priority
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<IssuePriority?> PriorityOption { get; private set; }

        /// <summary>
        /// Gets or Sets Priority
        /// </summary>
        [JsonPropertyName("priority")]
        public IssuePriority? Priority { get { return this.PriorityOption; } set { this.PriorityOption = new(value); } }

        /// <summary>
        /// Used to track the state of Assignment
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<AssignmentChange?> AssignmentOption { get; private set; }

        /// <summary>
        /// Gets or Sets Assignment
        /// </summary>
        [JsonPropertyName("assignment")]
        public AssignmentChange? Assignment { get { return this.AssignmentOption; } set { this.AssignmentOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UpdateIssueRequest {\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  Priority: ").Append(Priority).Append("\n");
            sb.Append("  Assignment: ").Append(Assignment).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="UpdateIssueRequest" />
    /// </summary>
    public class UpdateIssueRequestJsonConverter : JsonConverter<UpdateIssueRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="UpdateIssueRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override UpdateIssueRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<IssueType?> type = default;
            Option<IssueStatus?> status = default;
            Option<IssuePriority?> priority = default;
            Option<AssignmentChange?> assignment = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "type":
                            string? typeRawValue = utf8JsonReader.GetString();
                            if (typeRawValue != null)
                                type = new Option<IssueType?>(IssueTypeValueConverter.FromStringOrDefault(typeRawValue));
                            break;
                        case "status":
                            string? statusRawValue = utf8JsonReader.GetString();
                            if (statusRawValue != null)
                                status = new Option<IssueStatus?>(IssueStatusValueConverter.FromStringOrDefault(statusRawValue));
                            break;
                        case "priority":
                            string? priorityRawValue = utf8JsonReader.GetString();
                            if (priorityRawValue != null)
                                priority = new Option<IssuePriority?>(IssuePriorityValueConverter.FromStringOrDefault(priorityRawValue));
                            break;
                        case "assignment":
                            assignment = new Option<AssignmentChange?>(JsonSerializer.Deserialize<AssignmentChange>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            return new UpdateIssueRequest(type, status, priority, assignment);
        }

        /// <summary>
        /// Serializes a <see cref="UpdateIssueRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="updateIssueRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, UpdateIssueRequest updateIssueRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, updateIssueRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="UpdateIssueRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="updateIssueRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, UpdateIssueRequest updateIssueRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (updateIssueRequest.TypeOption.IsSet)
                if (updateIssueRequest.TypeOption!.Value != null)
                {
                    var typeRawValue = IssueTypeValueConverter.ToJsonValue(updateIssueRequest.TypeOption.Value!.Value);
                    writer.WriteString("type", typeRawValue);
                }
                else
                    writer.WriteNull("type");
            if (updateIssueRequest.StatusOption.IsSet)
                if (updateIssueRequest.StatusOption!.Value != null)
                {
                    var statusRawValue = IssueStatusValueConverter.ToJsonValue(updateIssueRequest.StatusOption.Value!.Value);
                    writer.WriteString("status", statusRawValue);
                }
                else
                    writer.WriteNull("status");
            if (updateIssueRequest.PriorityOption.IsSet)
                if (updateIssueRequest.PriorityOption!.Value != null)
                {
                    var priorityRawValue = IssuePriorityValueConverter.ToJsonValue(updateIssueRequest.PriorityOption.Value!.Value);
                    writer.WriteString("priority", priorityRawValue);
                }
                else
                    writer.WriteNull("priority");
            if (updateIssueRequest.AssignmentOption.IsSet)
                if (updateIssueRequest.AssignmentOption.Value != null)
                {
                    writer.WritePropertyName("assignment");
                    JsonSerializer.Serialize(writer, updateIssueRequest.Assignment, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("assignment");
        }
    }
}
