:: Generated by: https://openapi-generator.tech
::

@echo off

dotnet restore src\GotIssues.Contracts
dotnet build src\GotIssues.Contracts
echo Now, run the following to start the project: dotnet run -p src\GotIssues.Contracts\GotIssues.Contracts.csproj --launch-profile web.
echo.
