/*
 * Got Issues API
 *
 * A self-hosted, API-first issue and task tracker for internal engineering work.  This document is the product's user-facing documentation as well as its contract: every operation and schema is described for a reader who has never seen the implementation. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using GotIssues.Contracts.Attributes;
using GotIssues.Contracts.Models;

namespace GotIssues.Contracts.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public abstract class PlaceholderApiController : ControllerBase
    { 
        /// <summary>
        /// Create a placeholder record.
        /// </summary>
        /// <param name="createPlaceholderRequest"></param>
        /// <response code="201">The record was created.</response>
        /// <response code="400">The request was malformed or failed validation.</response>
        /// <response code="401">No credentials were supplied, or they were not valid.</response>
        [HttpPost]
        [Route("/placeholders")]
        [Authorize]
        [Consumes("application/json")]
        [ValidateModelState]
        [ProducesResponseType(statusCode: 201, type: typeof(Placeholder))]
        [ProducesResponseType(statusCode: 400, type: typeof(Problem))]
        [ProducesResponseType(statusCode: 401, type: typeof(Problem))]
        public abstract Task<IActionResult> CreatePlaceholder([FromBody]CreatePlaceholderRequest createPlaceholderRequest);

        /// <summary>
        /// List placeholder records.
        /// </summary>
        /// <remarks>Returns a page of placeholder records, newest first.</remarks>
        /// <param name="page">1-based page number. Out-of-range values are rejected with 400 rather than silently adjusted, matching pageSize. The upper bound exists so the constraint is expressible in the contract and enforced by generated clients; this API does not support paging beyond that depth. </param>
        /// <param name="pageSize">Records per page. The maximum is a declared constraint, so a larger value is rejected with 400 rather than silently reduced — a client asking for 10 000 and receiving 100 without being told is worse. Clients generated from this document enforce it before the request leaves them. </param>
        /// <response code="200">A page of placeholder records.</response>
        /// <response code="400">The request was malformed or failed validation.</response>
        /// <response code="401">No credentials were supplied, or they were not valid.</response>
        [HttpGet]
        [Route("/placeholders")]
        [Authorize]
        [ValidateModelState]
        [ProducesResponseType(statusCode: 200, type: typeof(PlaceholderPage))]
        [ProducesResponseType(statusCode: 400, type: typeof(Problem))]
        [ProducesResponseType(statusCode: 401, type: typeof(Problem))]
        public abstract Task<IActionResult> ListPlaceholders([FromQuery (Name = "page")][Range(1, 1000000)]int? page, [FromQuery (Name = "pageSize")][Range(1, 100)]int? pageSize);
    }
}
