/*
 * Got Issues API
 *
 * A self-hosted, API-first issue and task tracker for internal engineering work.  This document is the product's user-facing documentation as well as its contract: every operation and schema is described for a reader who has never seen the implementation. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using GotIssues.Contracts.Converters;

namespace GotIssues.Contracts.Models
{ 
    /// <summary>
    /// A change of assignment.  There are three ways to send this object and they mean two things:  | Sent | Meaning | | - -- | - -- | | &#x60;{\&quot;subject\&quot;: \&quot;alice\&quot;}&#x60; | assign to &#x60;alice&#x60; | | &#x60;{\&quot;subject\&quot;: null}&#x60; | unassign | | &#x60;{}&#x60; | **unassign** — an absent &#x60;subject&#x60; is read as null |  The third is worth stating plainly rather than leaving to be discovered: a client that forgets to send &#x60;subject&#x60; unassigns the issue and receives 200. The API cannot distinguish an omitted &#x60;subject&#x60; from an explicit null — that is the same limitation this object exists to work around one level up — so it is documented rather than rejected. Omit &#x60;assignment&#x60; entirely to leave the holder alone.  &#x60;subject&#x60; is deliberately **not** listed as required. In JSON Schema &#x60;required&#x60; means \&quot;the property must be present\&quot;, but the C# generator renders it as &#x60;[Required]&#x60;, which means \&quot;must not be null\&quot; — and null is precisely the value that unassigns. Listing it would reject the operation this object exists to express. 
    /// </summary>
    [DataContract]
    public class AssignmentChange : IEquatable<AssignmentChange>
    {
        /// <summary>
        /// The subject of the person to assign, or **null to unassign**.  Control characters are excluded, for the reason every other free-text field in this document excludes them: PostgreSQL cannot store &#x60;U+0000&#x60;, so without this the value reaches the database and fails as an unhandled error rather than as validation. A subject is a token claim and spans one line.  A subject with no user record is rejected with 400: this API assigns to people it has seen, and inventing one silently would produce an assignee no client could render. 
        /// </summary>
        /// <value>The subject of the person to assign, or **null to unassign**.  Control characters are excluded, for the reason every other free-text field in this document excludes them: PostgreSQL cannot store &#x60;U+0000&#x60;, so without this the value reaches the database and fails as an unhandled error rather than as validation. A subject is a token claim and spans one line.  A subject with no user record is rejected with 400: this API assigns to people it has seen, and inventing one silently would produce an assignee no client could render. </value>
        [RegularExpression("^[^\\u0000-\\u001F\\u007F]+$")]
        [MaxLength(255)]
        [DataMember(Name="subject", EmitDefaultValue=true)]
        public string? Subject { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AssignmentChange {\n");
            sb.Append("  Subject: ").Append(Subject).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            var options = new JsonSerializerOptions
            {
                WriteIndented = true
            };

            return JsonSerializer.Serialize(this, options);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((AssignmentChange)obj);
        }

        /// <summary>
        /// Returns true if AssignmentChange instances are equal
        /// </summary>
        /// <param name="other">Instance of AssignmentChange to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AssignmentChange other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Subject == other.Subject ||
                    Subject != null &&
                    Subject.Equals(other.Subject)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Subject != null)
                    hashCode = hashCode * 59 + Subject.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(AssignmentChange left, AssignmentChange right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(AssignmentChange left, AssignmentChange right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
