/*
 * Got Issues API
 *
 * A self-hosted, API-first issue and task tracker for internal engineering work.  This document is the product's user-facing documentation as well as its contract: every operation and schema is described for a reader who has never seen the implementation. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using GotIssues.Contracts.Converters;

namespace GotIssues.Contracts.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public class CreateIssueRequest : IEquatable<CreateIssueRequest>
    {
        /// <summary>
        /// A one-line summary. C0 control characters and DEL are excluded — see &#x60;Issue.title&#x60; for both reasons and for the limit this constraint deliberately stops at.  &#x60;U+0085&#x60; and &#x60;U+2028&#x60; are accepted: the constraint is the narrow, checkable one. 
        /// </summary>
        /// <value>A one-line summary. C0 control characters and DEL are excluded — see &#x60;Issue.title&#x60; for both reasons and for the limit this constraint deliberately stops at.  &#x60;U+0085&#x60; and &#x60;U+2028&#x60; are accepted: the constraint is the narrow, checkable one. </value>
        [Required]
        [RegularExpression("^[^\\u0000-\\u001F\\u007F]+$")]
        [StringLength(200, MinimumLength=1)]
        [DataMember(Name="title", EmitDefaultValue=false)]
        public string Title { get; set; }

        /// <summary>
        /// Optional free text; multi-line is expected. Explicitly null means the same as omitting it. 
        /// </summary>
        /// <value>Optional free text; multi-line is expected. Explicitly null means the same as omitting it. </value>
        [RegularExpression("^[^\\u0000]*$")]
        [MaxLength(10000)]
        [DataMember(Name="description", EmitDefaultValue=true)]
        public string? Description { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CreateIssueRequest {\n");
            sb.Append("  Title: ").Append(Title).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            var options = new JsonSerializerOptions
            {
                WriteIndented = true
            };

            return JsonSerializer.Serialize(this, options);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((CreateIssueRequest)obj);
        }

        /// <summary>
        /// Returns true if CreateIssueRequest instances are equal
        /// </summary>
        /// <param name="other">Instance of CreateIssueRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CreateIssueRequest other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Title == other.Title ||
                    Title != null &&
                    Title.Equals(other.Title)
                ) && 
                (
                    Description == other.Description ||
                    Description != null &&
                    Description.Equals(other.Description)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Title != null)
                    hashCode = hashCode * 59 + Title.GetHashCode();
                    if (Description != null)
                    hashCode = hashCode * 59 + Description.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(CreateIssueRequest left, CreateIssueRequest right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(CreateIssueRequest left, CreateIssueRequest right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
