/*
 * Got Issues API
 *
 * A self-hosted, API-first issue and task tracker for internal engineering work.  This document is the product's user-facing documentation as well as its contract: every operation and schema is described for a reader who has never seen the implementation. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using GotIssues.Contracts.Converters;

namespace GotIssues.Contracts.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public class CreateProjectRequest : IEquatable<CreateProjectRequest>
    {
        /// <summary>
        /// The key this project&#39;s issues are numbered under, for example &#x60;GOTI&#x60;. Cannot be changed afterwards, so it is worth choosing deliberately. 
        /// </summary>
        /// <value>The key this project&#39;s issues are numbered under, for example &#x60;GOTI&#x60;. Cannot be changed afterwards, so it is worth choosing deliberately. </value>
        [Required]
        [RegularExpression("^[A-Z][A-Z0-9]{1,9}$")]
        [StringLength(10, MinimumLength=2)]
        [DataMember(Name="key", EmitDefaultValue=false)]
        public string Key { get; set; }

        /// <summary>
        /// The project&#39;s display name. C0 control characters and DEL are excluded: &#x60;U+0000&#x60; cannot be stored by PostgreSQL at all, and the rest of the range carries tabs and line breaks a display name has no use for. 
        /// </summary>
        /// <value>The project&#39;s display name. C0 control characters and DEL are excluded: &#x60;U+0000&#x60; cannot be stored by PostgreSQL at all, and the rest of the range carries tabs and line breaks a display name has no use for. </value>
        [Required]
        [RegularExpression("^[^\\u0000-\\u001F\\u007F]+$")]
        [StringLength(200, MinimumLength=1)]
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CreateProjectRequest {\n");
            sb.Append("  Key: ").Append(Key).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            var options = new JsonSerializerOptions
            {
                WriteIndented = true
            };

            return JsonSerializer.Serialize(this, options);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((CreateProjectRequest)obj);
        }

        /// <summary>
        /// Returns true if CreateProjectRequest instances are equal
        /// </summary>
        /// <param name="other">Instance of CreateProjectRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CreateProjectRequest other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Key == other.Key ||
                    Key != null &&
                    Key.Equals(other.Key)
                ) && 
                (
                    Name == other.Name ||
                    Name != null &&
                    Name.Equals(other.Name)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Key != null)
                    hashCode = hashCode * 59 + Key.GetHashCode();
                    if (Name != null)
                    hashCode = hashCode * 59 + Name.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(CreateProjectRequest left, CreateProjectRequest right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(CreateProjectRequest left, CreateProjectRequest right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
