/*
 * Got Issues API
 *
 * A self-hosted, API-first issue and task tracker for internal engineering work.  This document is the product's user-facing documentation as well as its contract: every operation and schema is described for a reader who has never seen the implementation. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using GotIssues.Contracts.Converters;

namespace GotIssues.Contracts.Models
{ 
        /// <summary>
        /// Where the work stands. Any value may follow any other — there are no transition rules, by design.  `in_review` was considered and deliberately left out: it is the first status that invites the transition rules this API does not have. Adding it later is the additive direction. 
        /// </summary>
        /// <value>Where the work stands. Any value may follow any other — there are no transition rules, by design.  `in_review` was considered and deliberately left out: it is the first status that invites the transition rules this API does not have. Adding it later is the additive direction. </value>
        
        public enum IssueStatus
        {
            
            /// <summary>
            /// Enum OpenEnum for open
            /// </summary>
            [EnumMember(Value = "open")]
            OpenEnum = 1,
            
            /// <summary>
            /// Enum InProgressEnum for in_progress
            /// </summary>
            [EnumMember(Value = "in_progress")]
            InProgressEnum = 2,
            
            /// <summary>
            /// Enum DoneEnum for done
            /// </summary>
            [EnumMember(Value = "done")]
            DoneEnum = 3
        }
}
