/*
 * Got Issues API
 *
 * A self-hosted, API-first issue and task tracker for internal engineering work.  This document is the product's user-facing documentation as well as its contract: every operation and schema is described for a reader who has never seen the implementation. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using GotIssues.Contracts.Converters;

namespace GotIssues.Contracts.Models
{ 
        /// <summary>
        /// What kind of work this is. Two values, deliberately: `story` and `epic` imply a planning model this product does not have, and adding a value later is additive while renaming one is a breaking change for every generated client. 
        /// </summary>
        /// <value>What kind of work this is. Two values, deliberately: `story` and `epic` imply a planning model this product does not have, and adding a value later is additive while renaming one is a breaking change for every generated client. </value>
        
        public enum IssueType
        {
            
            /// <summary>
            /// Enum BugEnum for bug
            /// </summary>
            [EnumMember(Value = "bug")]
            BugEnum = 1,
            
            /// <summary>
            /// Enum TaskEnum for task
            /// </summary>
            [EnumMember(Value = "task")]
            TaskEnum = 2
        }
}
