/*
 * Got Issues API
 *
 * A self-hosted, API-first issue and task tracker for internal engineering work.  This document is the product's user-facing documentation as well as its contract: every operation and schema is described for a reader who has never seen the implementation. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using GotIssues.Contracts.Converters;

namespace GotIssues.Contracts.Models
{ 
    /// <summary>
    /// A unit of work inside a project.
    /// </summary>
    [DataContract]
    public class Issue : IEquatable<Issue>
    {
        /// <summary>
        /// The issue&#39;s identifier.
        /// </summary>
        /// <value>The issue&#39;s identifier.</value>
        [Required]
        [DataMember(Name="id", EmitDefaultValue=true)]
        public Guid Id { get; set; }

        /// <summary>
        /// The issue&#39;s key: the project&#39;s key, a hyphen, and the number allocated within that project. This is the identifier people quote. 
        /// </summary>
        /// <value>The issue&#39;s key: the project&#39;s key, a hyphen, and the number allocated within that project. This is the identifier people quote. </value>
        [Required]
        [RegularExpression("^[A-Z][A-Z0-9]{1,9}-[1-9][0-9]{0,8}$")]
        [DataMember(Name="key", EmitDefaultValue=false)]
        public string Key { get; set; }

        /// <summary>
        /// The key of the project this issue belongs to.
        /// </summary>
        /// <value>The key of the project this issue belongs to.</value>
        [Required]
        [RegularExpression("^[A-Z][A-Z0-9]{1,9}$")]
        [DataMember(Name="projectKey", EmitDefaultValue=false)]
        public string ProjectKey { get; set; }

        /// <summary>
        /// The issue&#39;s number within its project. Allocated by the server, starting at 1 in each project, and never reused.  The maximum is not arbitrary: it is the largest number &#x60;key&#x60; can express, since that pattern allows nine digits. Without it the two fields could disagree — a number of ten digits would produce a key violating the very pattern this document declares, and the issue would be unreadable through the only operation that fetches one. A project reaching this limit is refused with 409 rather than issued a key it cannot use. 
        /// </summary>
        /// <value>The issue&#39;s number within its project. Allocated by the server, starting at 1 in each project, and never reused.  The maximum is not arbitrary: it is the largest number &#x60;key&#x60; can express, since that pattern allows nine digits. Without it the two fields could disagree — a number of ten digits would produce a key violating the very pattern this document declares, and the issue would be unreadable through the only operation that fetches one. A project reaching this limit is refused with 409 rather than issued a key it cannot use. </value>
        [Required]
        [Range(1, 999999999)]
        [DataMember(Name="number", EmitDefaultValue=true)]
        public int Number { get; set; }

        /// <summary>
        /// A one-line summary. C0 control characters and DEL are excluded, for the same two reasons a project name excludes them: PostgreSQL cannot store &#x60;U+0000&#x60; at all, and the ASCII line breaks and tabs in that range have no place in a title.  Deliberately **not** full Unicode line-break handling: &#x60;U+0085&#x60; and &#x60;U+2028&#x60; are accepted. Refinement asked this ticket to decide rather than inherit the limit, and the decision is to keep the constraint the narrow, checkable one — a title carrying an exotic separator is a cosmetic problem, while a title carrying &#x60;U+0000&#x60; cannot be stored at all. 
        /// </summary>
        /// <value>A one-line summary. C0 control characters and DEL are excluded, for the same two reasons a project name excludes them: PostgreSQL cannot store &#x60;U+0000&#x60; at all, and the ASCII line breaks and tabs in that range have no place in a title.  Deliberately **not** full Unicode line-break handling: &#x60;U+0085&#x60; and &#x60;U+2028&#x60; are accepted. Refinement asked this ticket to decide rather than inherit the limit, and the decision is to keep the constraint the narrow, checkable one — a title carrying an exotic separator is a cosmetic problem, while a title carrying &#x60;U+0000&#x60; cannot be stored at all. </value>
        [Required]
        [RegularExpression("^[^\\u0000-\\u001F\\u007F]+$")]
        [StringLength(200, MinimumLength=1)]
        [DataMember(Name="title", EmitDefaultValue=false)]
        public string Title { get; set; }

        /// <summary>
        /// Optional free text. Multi-line **by design** — unlike a title, this is where the reasoning goes, so line breaks are permitted and only &#x60;U+0000&#x60; is excluded, because PostgreSQL cannot store it in any text column.  That difference is deliberate: the constraint on a title is about being one line, the constraint here is about being storable, and they are not the same rule (recorded on T-0005 from T-0004&#39;s review). 
        /// </summary>
        /// <value>Optional free text. Multi-line **by design** — unlike a title, this is where the reasoning goes, so line breaks are permitted and only &#x60;U+0000&#x60; is excluded, because PostgreSQL cannot store it in any text column.  That difference is deliberate: the constraint on a title is about being one line, the constraint here is about being storable, and they are not the same rule (recorded on T-0005 from T-0004&#39;s review). </value>
        [RegularExpression("^[^\\u0000]*$")]
        [MaxLength(10000)]
        [DataMember(Name="description", EmitDefaultValue=true)]
        public string? Description { get; set; }

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [Required]
        [DataMember(Name="type", EmitDefaultValue=true)]
        public IssueType Type { get; set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [Required]
        [DataMember(Name="status", EmitDefaultValue=true)]
        public IssueStatus Status { get; set; }

        /// <summary>
        /// Gets or Sets Priority
        /// </summary>
        [Required]
        [DataMember(Name="priority", EmitDefaultValue=true)]
        public IssuePriority Priority { get; set; }

        /// <summary>
        /// Gets or Sets Assignee
        /// </summary>
        [DataMember(Name="assignee", EmitDefaultValue=true)]
        public Assignee Assignee { get; set; }

        /// <summary>
        /// When the issue was created, in UTC.
        /// </summary>
        /// <value>When the issue was created, in UTC.</value>
        [Required]
        [DataMember(Name="createdAt", EmitDefaultValue=true)]
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Issue {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Key: ").Append(Key).Append("\n");
            sb.Append("  ProjectKey: ").Append(ProjectKey).Append("\n");
            sb.Append("  Number: ").Append(Number).Append("\n");
            sb.Append("  Title: ").Append(Title).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  Priority: ").Append(Priority).Append("\n");
            sb.Append("  Assignee: ").Append(Assignee).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            var options = new JsonSerializerOptions
            {
                WriteIndented = true
            };

            return JsonSerializer.Serialize(this, options);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((Issue)obj);
        }

        /// <summary>
        /// Returns true if Issue instances are equal
        /// </summary>
        /// <param name="other">Instance of Issue to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Issue other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Id == other.Id ||
                    
                    Id.Equals(other.Id)
                ) && 
                (
                    Key == other.Key ||
                    Key != null &&
                    Key.Equals(other.Key)
                ) && 
                (
                    ProjectKey == other.ProjectKey ||
                    ProjectKey != null &&
                    ProjectKey.Equals(other.ProjectKey)
                ) && 
                (
                    Number == other.Number ||
                    
                    Number.Equals(other.Number)
                ) && 
                (
                    Title == other.Title ||
                    Title != null &&
                    Title.Equals(other.Title)
                ) && 
                (
                    Description == other.Description ||
                    Description != null &&
                    Description.Equals(other.Description)
                ) && 
                (
                    Type == other.Type ||
                    
                    Type.Equals(other.Type)
                ) && 
                (
                    Status == other.Status ||
                    
                    Status.Equals(other.Status)
                ) && 
                (
                    Priority == other.Priority ||
                    
                    Priority.Equals(other.Priority)
                ) && 
                (
                    Assignee == other.Assignee ||
                    Assignee != null &&
                    Assignee.Equals(other.Assignee)
                ) && 
                (
                    CreatedAt == other.CreatedAt ||
                    
                    CreatedAt.Equals(other.CreatedAt)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    
                    hashCode = hashCode * 59 + Id.GetHashCode();
                    if (Key != null)
                    hashCode = hashCode * 59 + Key.GetHashCode();
                    if (ProjectKey != null)
                    hashCode = hashCode * 59 + ProjectKey.GetHashCode();
                    
                    hashCode = hashCode * 59 + Number.GetHashCode();
                    if (Title != null)
                    hashCode = hashCode * 59 + Title.GetHashCode();
                    if (Description != null)
                    hashCode = hashCode * 59 + Description.GetHashCode();
                    
                    hashCode = hashCode * 59 + Type.GetHashCode();
                    
                    hashCode = hashCode * 59 + Status.GetHashCode();
                    
                    hashCode = hashCode * 59 + Priority.GetHashCode();
                    if (Assignee != null)
                    hashCode = hashCode * 59 + Assignee.GetHashCode();
                    
                    hashCode = hashCode * 59 + CreatedAt.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(Issue left, Issue right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(Issue left, Issue right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
