/*
 * Got Issues API
 *
 * A self-hosted, API-first issue and task tracker for internal engineering work.  This document is the product's user-facing documentation as well as its contract: every operation and schema is described for a reader who has never seen the implementation. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using GotIssues.Contracts.Converters;

namespace GotIssues.Contracts.Models
{ 
    /// <summary>
    /// A project, which groups related work and owns the key its issues are numbered under.
    /// </summary>
    [DataContract]
    public class Project : IEquatable<Project>
    {
        /// <summary>
        /// The project&#39;s identifier.
        /// </summary>
        /// <value>The project&#39;s identifier.</value>
        [Required]
        [DataMember(Name="id", EmitDefaultValue=true)]
        public Guid Id { get; set; }

        /// <summary>
        /// The project&#39;s key: 2-10 characters, uppercase letters and digits, starting with a letter. Unique across the deployment and immutable once set. 
        /// </summary>
        /// <value>The project&#39;s key: 2-10 characters, uppercase letters and digits, starting with a letter. Unique across the deployment and immutable once set. </value>
        [Required]
        [RegularExpression("^[A-Z][A-Z0-9]{1,9}$")]
        [StringLength(10, MinimumLength=2)]
        [DataMember(Name="key", EmitDefaultValue=false)]
        public string Key { get; set; }

        /// <summary>
        /// The project&#39;s display name. Names need not be unique — the key is the identifier, and requiring unique names would be a constraint on people rather than on data.  C0 control characters and DEL are excluded. Two reasons, and they are not the same reason: PostgreSQL cannot store &#x60;U+0000&#x60; in text at all, so a name carrying one fails as an unhandled error rather than as validation; and the rest of the range carries tabs and line breaks, which a display name has no use for.  This is not full Unicode line-break normalisation — &#x60;U+0085&#x60; and &#x60;U+2028&#x60; are accepted. The constraint is deliberately the narrow, checkable one. 
        /// </summary>
        /// <value>The project&#39;s display name. Names need not be unique — the key is the identifier, and requiring unique names would be a constraint on people rather than on data.  C0 control characters and DEL are excluded. Two reasons, and they are not the same reason: PostgreSQL cannot store &#x60;U+0000&#x60; in text at all, so a name carrying one fails as an unhandled error rather than as validation; and the rest of the range carries tabs and line breaks, which a display name has no use for.  This is not full Unicode line-break normalisation — &#x60;U+0085&#x60; and &#x60;U+2028&#x60; are accepted. The constraint is deliberately the narrow, checkable one. </value>
        [Required]
        [RegularExpression("^[^\\u0000-\\u001F\\u007F]+$")]
        [StringLength(200, MinimumLength=1)]
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// When the project was created, in UTC.
        /// </summary>
        /// <value>When the project was created, in UTC.</value>
        [Required]
        [DataMember(Name="createdAt", EmitDefaultValue=true)]
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Project {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Key: ").Append(Key).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            var options = new JsonSerializerOptions
            {
                WriteIndented = true
            };

            return JsonSerializer.Serialize(this, options);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((Project)obj);
        }

        /// <summary>
        /// Returns true if Project instances are equal
        /// </summary>
        /// <param name="other">Instance of Project to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Project other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Id == other.Id ||
                    
                    Id.Equals(other.Id)
                ) && 
                (
                    Key == other.Key ||
                    Key != null &&
                    Key.Equals(other.Key)
                ) && 
                (
                    Name == other.Name ||
                    Name != null &&
                    Name.Equals(other.Name)
                ) && 
                (
                    CreatedAt == other.CreatedAt ||
                    
                    CreatedAt.Equals(other.CreatedAt)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    
                    hashCode = hashCode * 59 + Id.GetHashCode();
                    if (Key != null)
                    hashCode = hashCode * 59 + Key.GetHashCode();
                    if (Name != null)
                    hashCode = hashCode * 59 + Name.GetHashCode();
                    
                    hashCode = hashCode * 59 + CreatedAt.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(Project left, Project right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(Project left, Project right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
